/* this code was autogenerated by p2iOS */
#include <p2iOS.h>

namespace p2iOS_user {

;

;

void p2iOS_init() {
    ;
};

void setup();
void drawCircle(float x, float y, int radius, int level);
void draw() { };

void setup() {
    p2iOS::size(200, 200);
    p2iOS::noStroke();
    p2iOS::smooth();
    drawCircle(100, 100, 80, 8);
}

void drawCircle(float x, float y, int radius, int level) {
    float tt =  126 * level/6.0;
    p2iOS::fill(tt, 153);
    p2iOS::ellipse(x, y, radius*2, radius*2);
    if(level > 1) {
        level = level - 1;
        int num =  int(p2iOS::random(2, 6));
        for(int i = 0;  i<num;  i++) {
            float a =  p2iOS::random(0, p2iOS::TWO_PI);
            float nx =  x + p2iOS::cos(a) * 6.0 * level;
            float ny =  y + p2iOS::sin(a) * 6.0 * level;
            drawCircle(nx, ny, radius/2, level);
        }
    }
}

}

P2IOS_MAIN
